# test yaml 用于设置test相关的参数，开源版本需要去掉参数
token:
  appid: "102460390"
  token: "8JSkfTvKydCMDfUvn1eCARLr6xU6MdbA"
  secret: "5JXlzDShwBQfu9OeuAQgwCSizGXo5Mdu"
test_params:
  guild_id: "895102701"
  guild_owner_id: "3399588151"
  guild_owner_name: "ArdentlyLov"
  guild_test_member_id: "123"
  guild_test_role_id: "123"
  channel_id: "123"
  channel_name: "channel"
  channel_schedule_id: "123"
  robot_name: "Liang robot"
  is_sandbox: False
  message_id: "123"
